apiVersion: 1

datasources:
  - name: ClickHouse
    uid: aegis-clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    user: ${CLICKHOUSE_USER}
    database: ${CLICKHOUSE_DB}
    isDefault: true
    editable: false
    jsonData:
      defaultDatabase: ${CLICKHOUSE_DB}
      server: clickhouse
      port: 8123
      protocol: http
      username: ${CLICKHOUSE_USER}
      tlsSkipVerify: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
