name: ${COMPOSE_PROJECT_NAME:-aegis-vanguard}

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.3
    profiles:
      - elastic
    restart: "no"
    environment:
      ELASTIC_PASSWORD_FILE: /run/secrets/elasticsearch-bootstrap-password
    secrets:
      - elasticsearch-bootstrap-password
    volumes:
      - type: volume
        source: elasticsearch-data
        target: /usr/share/elasticsearch/data
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: ./elasticsearch/bin/elasticsearch-healthcheck.sh
        target: /usr/local/bin/elasticsearch-healthcheck.sh
        read_only: true
      - type: bind
        source: ./tls/generated/ca
        target: /usr/share/elasticsearch/config/certs/ca
        read_only: true
      - type: bind
        source: ./tls/generated/elasticsearch
        target: /usr/share/elasticsearch/config/certs/elasticsearch
        read_only: true
    ports:
      - name: elasticsearch-https
        target: 9200
        published: "9200"
        host_ip: 192.168.15.1
        protocol: tcp
    networks:
      - phase1
    healthcheck:
      test:
        - CMD
        - /bin/sh
        - /usr/local/bin/elasticsearch-healthcheck.sh
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 30

  kibana:
    image: docker.elastic.co/kibana/kibana:9.4.3
    profiles:
      - elastic
    restart: "no"
    depends_on:
      elasticsearch:
        condition: service_healthy
        restart: true
    volumes:
      - type: volume
        source: kibana-data
        target: /usr/share/kibana/data
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
      - type: bind
        source: ./kibana/config/kibana.keystore
        target: /usr/share/kibana/config/kibana.keystore
        read_only: true
      - type: bind
        source: ./kibana/bin/kibana-healthcheck.js
        target: /usr/local/bin/kibana-healthcheck.js
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ./tls/generated/ca
        target: /usr/share/kibana/config/certs/ca
        read_only: true
    ports:
      - name: kibana-http
        target: 5601
        published: "5601"
        host_ip: 127.0.0.1
        protocol: tcp
    networks:
      - phase1
    healthcheck:
      test:
        - CMD
        - /usr/share/kibana/node/bin/node
        - /usr/local/bin/kibana-healthcheck.js
      interval: 10s
      timeout: 8s
      retries: 30
      start_period: 60s

secrets:
  elasticsearch-bootstrap-password:
    file: ./secrets/elasticsearch-bootstrap-password.txt

volumes:
  elasticsearch-data:
  kibana-data:

networks:
  phase1:
    driver: bridge
    internal: false
    external: false
