server.name: kibana
server.host: 0.0.0.0
server.port: 5601

elasticsearch.hosts:
  - https://elasticsearch:9200
elasticsearch.ssl.certificateAuthorities:
  - /usr/share/kibana/config/certs/ca/ca.crt
elasticsearch.ssl.verificationMode: full

telemetry.optIn: false
