[CmdletBinding()]
param(
    [string]$EvidenceDirectory,
    [string]$RulesDirectory,
    [string]$OutputPath
)

# Builds mitre/coverage.md from evidence bundles only.
#
# The point of this script is what it refuses to do: a technique appears as covered
# only when a scenario bundle recorded a `detected` result for it. Rules that exist but
# have never fired are listed separately as claimed-but-unproven, and rules with no
# bundle at all are listed as untested. Nothing here is hand-maintained, so the matrix
# cannot drift away from the evidence.

$ErrorActionPreference = 'Stop'

$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).ProviderPath
if (-not $EvidenceDirectory) { $EvidenceDirectory = Join-Path $repositoryRoot 'evidence' }
if (-not $RulesDirectory) { $RulesDirectory = Join-Path $repositoryRoot 'rules\windows' }
if (-not $OutputPath) { $OutputPath = Join-Path $repositoryRoot 'mitre\coverage.md' }

# --- Rules declared in the repository --------------------------------------------------
$declaredRules = @(
    Get-ChildItem -LiteralPath $RulesDirectory -Filter '*.yml' -ErrorAction SilentlyContinue | ForEach-Object {
        $text = Get-Content -LiteralPath $_.FullName -Raw

        $title = if ($text -match '(?m)^title:\s*(.+)$') { $Matches[1].Trim() } else { $_.BaseName }
        $ruleId = if ($text -match '(?m)^id:\s*(.+)$') { $Matches[1].Trim() } else { '' }
        $level = if ($text -match '(?m)^level:\s*(.+)$') { $Matches[1].Trim() } else { 'unknown' }

        # attack.tXXXX.XXX tags carry the technique; everything else in tags is tactic noise.
        $techniques = @(
            [regex]::Matches($text, '(?im)^\s*-\s*attack\.(t\d{4}(?:\.\d{3})?)\s*$') |
                ForEach-Object { $_.Groups[1].Value.ToUpperInvariant() }
        )

        [pscustomobject]@{
            Title      = $title
            RuleId     = $ruleId
            Level      = $level
            Techniques = $techniques
            File       = "rules/windows/$($_.Name)"
        }
    }
)

# --- Evidence bundles ------------------------------------------------------------------
$bundles = @(
    Get-ChildItem -LiteralPath $EvidenceDirectory -Filter '*-raw.json' -ErrorAction SilentlyContinue | ForEach-Object {
        $bundle = Get-Content -LiteralPath $_.FullName -Raw | ConvertFrom-Json
        [pscustomobject]@{
            ScenarioId  = $bundle.scenario_id
            TechniqueId = $bundle.technique_id
            RuleId      = $bundle.rule.rule_id
            RuleName    = $bundle.rule.name
            Result      = $bundle.detection_result
            AlertCount  = $bundle.alert_count
            Mttd        = $bundle.time_to_detect_s
            AtomicTest  = $bundle.atomic_test
            Report      = "evidence/$($bundle.scenario_id).md"
        }
    }
)

$detectedBundles = @($bundles | Where-Object { $_.Result -eq 'detected' })

# --- Report ----------------------------------------------------------------------------
$lines = [System.Collections.Generic.List[string]]::new()
function Add-Line { param([string]$Text = '') $lines.Add($Text) | Out-Null }

Add-Line '# MITRE ATT&CK coverage'
Add-Line
Add-Line "<!-- Generated by scripts/build-coverage.ps1 on $([datetime]::UtcNow.ToString('o')). Do not edit by hand. -->"
Add-Line
Add-Line 'Every row below is derived from an evidence bundle in `evidence/`. A technique is'
Add-Line 'listed as covered only because a scenario produced a `detected` result for it, never'
Add-Line 'because a rule exists.'
Add-Line

# A bundle only counts toward Live verified when the activity was defined by an external
# Atomic Red Team test rather than by a marker this project wrote to match its own rule.
$atomicBundles = @($detectedBundles | Where-Object { $_.AtomicTest -and $_.AtomicTest -notmatch '^not applicable' })
$markerBundles = @($detectedBundles | Where-Object { -not $_.AtomicTest -or $_.AtomicTest -match '^not applicable' })

Add-Line '## What this matrix does not mean'
Add-Line
Add-Line '- Coverage of a technique here means **one** specific behaviour was detected once, in'
Add-Line '  one lab, on one host. It does not mean the technique is covered in general; each'
Add-Line '  technique has many procedures and this lab exercises one.'
Add-Line '- Detection here says nothing about whether the rule would survive an attacker who is'
Add-Line '  actively trying to evade it.'
Add-Line '- A benign marker run is the weakest possible test, because the same person wrote the'
Add-Line '  rule and the activity meant to trigger it. Only an externally defined Atomic Red Team'
Add-Line '  test removes that circularity, which is why the two are counted separately below.'
Add-Line

Add-Line '## Live verified eligibility'
Add-Line
Add-Line '| Basis | Scenarios | Counts toward `Live verified` |'
Add-Line '| --- | --- | --- |'
Add-Line ('| Approved Atomic Red Team test | {0} | yes |' -f $atomicBundles.Count)
Add-Line ('| Benign marker written by this project | {0} | no |' -f $markerBundles.Count)
Add-Line

if ($atomicBundles.Count -gt 0) {
    Add-Line 'Atomic-backed rule-scenario pairs:'
    Add-Line
    foreach ($bundle in $atomicBundles) {
        Add-Line ('- `{0}` - {1} on `{2}`, via {3}' -f $bundle.ScenarioId, $bundle.RuleName, $bundle.TechniqueId, $bundle.AtomicTest)
    }
    Add-Line
    Add-Line 'Each pair above is `Live verified` **only as that exact pair**. Per `PROJECT_PLAN.md`'
    Add-Line 'this must never be generalised to the phase, the platform, the rule collection, or the'
    Add-Line 'technique as a whole.'
}
else {
    Add-Line 'No entry is `Live verified`: every scenario so far is a benign marker run.'
}
Add-Line

Add-Line '## Evidence-backed coverage'
Add-Line

if ($detectedBundles.Count -eq 0) {
    Add-Line '_No technique has an evidence-backed detection yet._'
    Add-Line
}
else {
    Add-Line '| Technique | Scenario | Rule | Alerts | Time to detect (s) | Atomic test | Evidence |'
    Add-Line '| --- | --- | --- | --- | --- | --- | --- |'
    foreach ($bundle in ($detectedBundles | Sort-Object TechniqueId)) {
        Add-Line ('| [`{0}`](https://attack.mitre.org/techniques/{1}/) | `{2}` | {3} | {4} | {5} | {6} | [{7}]({7}) |' -f `
            $bundle.TechniqueId, `
            ($bundle.TechniqueId -replace '\.', '/'), `
            $bundle.ScenarioId, `
            $bundle.RuleName, `
            $bundle.AlertCount, `
            $bundle.Mttd, `
            $bundle.AtomicTest, `
            $bundle.Report)
    }
    Add-Line
}

# --- Rules without evidence -------------------------------------------------------------
$provenRuleIds = @($detectedBundles | ForEach-Object { $_.RuleId } | Sort-Object -Unique)
$unprovenRules = @($declaredRules | Where-Object { $_.RuleId -notin $provenRuleIds })

Add-Line '## Rules with no evidence-backed detection'
Add-Line

if ($unprovenRules.Count -eq 0) {
    Add-Line '_Every declared rule has produced at least one evidence-backed detection._'
    Add-Line
}
else {
    Add-Line 'These rules exist and pass their fixture checks, but have never matched real telemetry.'
    Add-Line 'They are `Unit tested`, not `Runtime verified`, and contribute nothing to coverage.'
    Add-Line
    Add-Line '| Rule | Techniques | Severity | Why there is no evidence |'
    Add-Line '| --- | --- | --- | --- |'
    foreach ($rule in $unprovenRules) {
        $reason = if ($rule.Techniques -contains 'T1218.010') {
            'Triggering it requires fetching a remote scriptlet; the host-only lab correctly has no egress'
        }
        else {
            'No scenario has exercised this rule yet'
        }

        Add-Line ('| [{0}]({1}) | {2} | {3} | {4} |' -f `
            $rule.Title, $rule.File, (($rule.Techniques | ForEach-Object { "``$_``" }) -join ', '), $rule.Level, $reason)
    }
    Add-Line
}

# --- Missed and partial results ----------------------------------------------------------
$notDetected = @($bundles | Where-Object { $_.Result -ne 'detected' })
if ($notDetected.Count -gt 0) {
    Add-Line '## Scenarios that did not detect'
    Add-Line
    Add-Line '| Scenario | Technique | Result | Evidence |'
    Add-Line '| --- | --- | --- | --- |'
    foreach ($bundle in $notDetected) {
        Add-Line ('| `{0}` | `{1}` | **{2}** | [{3}]({3}) |' -f $bundle.ScenarioId, $bundle.TechniqueId, $bundle.Result, $bundle.Report)
    }
    Add-Line
}

# --- Totals -------------------------------------------------------------------------------
$coveredTechniques = @($detectedBundles | ForEach-Object { $_.TechniqueId } | Sort-Object -Unique)
$declaredTechniques = @($declaredRules | ForEach-Object { $_.Techniques } | Sort-Object -Unique)

Add-Line '## Totals'
Add-Line
Add-Line '| Measure | Value |'
Add-Line '| --- | --- |'
Add-Line "| Rules declared | $($declaredRules.Count) |"
Add-Line "| Techniques referenced by rules | $($declaredTechniques.Count) |"
Add-Line "| Techniques with an evidence-backed detection | $($coveredTechniques.Count) |"
Add-Line "| Evidence bundles | $($bundles.Count) |"
Add-Line ('| Bundles with result `detected` | {0} |' -f $detectedBundles.Count)
Add-Line
Add-Line 'Coverage is deliberately reported as counts, not as a percentage. A ratio here would'
Add-Line 'imply a denominator of "all techniques an attacker could use", which this lab has no'
Add-Line 'basis to state. Per `PROJECT_PLAN.md`, all coverage metrics remain `Not measured yet`.'

$outputDirectory = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}
Set-Content -LiteralPath $OutputPath -Value $lines -Encoding utf8

Write-Host "PASS: coverage matrix written to $OutputPath" -ForegroundColor Green
Write-Host "  rules declared                 : $($declaredRules.Count)"
Write-Host "  evidence bundles               : $($bundles.Count)"
Write-Host "  techniques with evidence       : $($coveredTechniques.Count)"
Write-Host "  rules without evidence         : $($unprovenRules.Count)"
exit 0
